var perks_desc = {
  'CBF': 'Complementary Breakfast',
  'CRU': 'Room Upgrades',
  'ECI': 'Early Check-in',
  'LCO': 'Late Check-out',
  'FCD': 'Free Credit',
  // 'WGA': 'Welcome Amenities',
  // 'CIN': 'Complementary Internet',
  'OTH': 'Others',
};

var perks_icon = {
  'CBF': './resources/logo_favicon/CBF.png',
  'CRU': './resources/logo_favicon/CRU.png',
  'ECI': './resources/logo_favicon/ECI.png',
  'LCO': './resources/logo_favicon/LCO.png',
  'FCD': './resources/logo_favicon/FCD.png',
  // 'WGA': './resources/logo_favicon/WGA.png',
  // 'CIN': './resources/logo_favicon/CIN.png',
  'OTH': './resources/logo_favicon/OTH.png',
};

var elite_desc = {
  'EP00FH': 'AMEX Fine Hotels + Resorts',
  'EP00HC': 'AMEX The Hotel Collection',
  'HC00BM': 'Belmond Bellini Club',
  'HC00DC': 'Dorchester Diamond Club',
  'HC00FS': 'Four Seasons Preferred Partners',
  'HC00HT': 'Hilton Impresario',
  'HC00HY': 'Hyatt Prive',
  'HCLFIC': 'IHG Lifestyle',
  'HCLXIC': 'IHG Luxury',
  'HC00MO': 'Mandarin Oriental Fan Club',
  'HCSTMR': 'Marriott STARS',
  'HCLUMR': 'Marriott Luminous',
  'HC00OR': 'Oetker Pearl Partner',
  'HC00PE': 'Peninsula PenClub',
  'EP00PP': 'Preferred Platinum Partner',
  'HC00RW': 'Rosewood Elite',
  'EP00SL': 'Small Luxury Hotels withIN',
  'EP00VT': 'Virtuoso',
}

var elite_icon = {
  'EP00FH': './resources/logo_favicon/EP00FH.png',
  'EP00HC': './resources/logo_favicon/EP00HC.png',
  'EP00VT': './resources/logo_favicon/EP00VT.png',
  'HC00HY': './resources/logo_favicon/HC00HY.png',
  // 'HC00MR': './resources/logo_favicon/HC00MR.png',
  'HC00FS': './resources/logo_favicon/HC00FS.png',
  'HCSTMR': './resources/logo_favicon/HCSTMR.png',
  'HCLUMR': './resources/logo_favicon/HCLUMR.png',
  'HC00HT': './resources/logo_favicon/HC00HT.png',
  'HC00MO': './resources/logo_favicon/HC00MO.png',
  'EP00SL': './resources/logo_favicon/EP00SL.png',
  'HC00RW': './resources/logo_favicon/HC00RW.png',
  'HC00PE': './resources/logo_favicon/HC00PE.png',
  'HC00OR': './resources/logo_favicon/HC00OR.png',
  'HCLXIC': './resources/logo_favicon/HCLXIC.png',
  'HCLFIC': './resources/logo_favicon/HCLFIC.png',
  'HC00DC': './resources/logo_favicon/HC00DC.png',
  'HC00BM': './resources/logo_favicon/HC00BM.png',
  'EP00PP': './resources/logo_favicon/EP00PP.png',
}
